# Generated by Django 4.2 on 2024-10-14 09:13

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('list_position', models.IntegerField(unique=True)),
                ('list_image', models.ImageField(blank=True, null=True, upload_to='project_images')),
            ],
            options={
                'ordering': ['list_position'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255)),
                ('html_content', models.TextField()),
                ('css_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_custom_html', models.BooleanField(default=False)),
                ('custom_html', models.TextField(blank=True, null=True)),
                ('html_description_name', models.CharField(blank=True, max_length=255, null=True)),
                ('use_custom_css', models.BooleanField(default=False)),
                ('custom_css', models.TextField(blank=True, null=True)),
                ('project_description_1', models.TextField(blank=True, null=True)),
                ('project_description_2', models.TextField(blank=True, null=True)),
                ('change_header_color', models.BooleanField(default=False)),
                ('new_header_color', models.CharField(blank=True, max_length=200, null=True)),
                ('new_header_color_hover', models.CharField(blank=True, max_length=200, null=True)),
                ('change_text_color', models.BooleanField(default=False)),
                ('new_text_color', models.CharField(blank=True, max_length=200, null=True)),
                ('img_1', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('img_1_tablet', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('img_1_mobile', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('img_1_description', models.TextField(blank=True, null=True)),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('img_2_tablet', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('img_2_mobile', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('img_2_description', models.TextField(blank=True, null=True)),
                ('img_3', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('img_3_tablet', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('img_3_mobile', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('img_3_description', models.TextField(blank=True, null=True)),
                ('img_4', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('img_4_tablet', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('img_4_mobile', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('img_4_description', models.TextField(blank=True, null=True)),
                ('img_5', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('img_5_tablet', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('img_5_mobile', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('img_5_description', models.TextField(blank=True, null=True)),
                ('img_6', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('img_6_tablet', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('img_6_mobile', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('img_6_description', models.TextField(blank=True, null=True)),
                ('img_7', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('img_7_tablet', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('img_7_mobile', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('img_7_description', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.template')),
            ],
            options={
                'verbose_name': 'Project Page Section',
                'verbose_name_plural': 'Project Page Sections',
            },
            bases=(projects.models.SectionCleanMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('section_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_1', to='projects.section')),
                ('section_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_2', to='projects.section')),
                ('section_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_3', to='projects.section')),
                ('section_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_4', to='projects.section')),
                ('section_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_5', to='projects.section')),
                ('section_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_6', to='projects.section')),
                ('section_7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_7', to='projects.section')),
                ('section_8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_8', to='projects.section')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='main_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_service', to='projects.service'),
        ),
        migrations.AddField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(related_name='secondary_services', to='projects.service'),
        ),
    ]
