# Generated by Django 4.2 on 2024-10-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='css_content',
            field=models.TextField(null=True),
        ),
    ]
