# Generated by Django 4.2 on 2024-10-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_template_css_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='new_text_color_mobile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='new_text_color_tablet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='css_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
