# Generated by Django 4.2 on 2024-10-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_section_new_text_color_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='new_header_color_hover_mobile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='new_header_color_hover_tablet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='new_header_color_mobile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='new_header_color_tablet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
