# Generated by Django 4.2 on 2024-11-01 19:20

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectpage_section_10_projectpage_section_9'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='template_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='section_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_1', to='projects.section'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='section_10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_10', to='projects.section'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='section_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_2', to='projects.section'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='section_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_3', to='projects.section'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='section_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_4', to='projects.section'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='section_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_5', to='projects.section'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='section_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_6', to='projects.section'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='section_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_7', to='projects.section'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='section_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_8', to='projects.section'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='section_9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_9', to='projects.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='video_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
