# Generated by Django 4.2 on 2024-11-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_template_template_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['template_name']},
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
