# Generated by Django 4.2 on 2024-11-21 15:40

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_template_options_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='list_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/list_images'),
        ),
        migrations.AlterField(
            model_name='section',
            name='img_1',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.get_unique_image_name),
        ),
        migrations.AlterField(
            model_name='section',
            name='img_1_mobile',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.get_unique_image_name),
        ),
        migrations.AlterField(
            model_name='section',
            name='img_1_tablet',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.get_unique_image_name),
        ),
        migrations.AlterField(
            model_name='section',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.get_unique_image_name),
        ),
        migrations.AlterField(
            model_name='section',
            name='img_2_mobile',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.get_unique_image_name),
        ),
        migrations.AlterField(
            model_name='section',
            name='img_2_tablet',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.get_unique_image_name),
        ),
        migrations.AlterField(
            model_name='section',
            name='img_3',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.get_unique_image_name),
        ),
        migrations.AlterField(
            model_name='section',
            name='img_3_mobile',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.get_unique_image_name),
        ),
        migrations.AlterField(
            model_name='section',
            name='img_3_tablet',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.get_unique_image_name),
        ),
        migrations.AlterField(
            model_name='section',
            name='img_4',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.get_unique_image_name),
        ),
        migrations.AlterField(
            model_name='section',
            name='img_4_mobile',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.get_unique_image_name),
        ),
        migrations.AlterField(
            model_name='section',
            name='img_4_tablet',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.get_unique_image_name),
        ),
        migrations.AlterField(
            model_name='section',
            name='img_5',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.get_unique_image_name),
        ),
        migrations.AlterField(
            model_name='section',
            name='img_5_mobile',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.get_unique_image_name),
        ),
        migrations.AlterField(
            model_name='section',
            name='img_5_tablet',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.get_unique_image_name),
        ),
        migrations.AlterField(
            model_name='section',
            name='img_6',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.get_unique_image_name),
        ),
        migrations.AlterField(
            model_name='section',
            name='img_6_mobile',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.get_unique_image_name),
        ),
        migrations.AlterField(
            model_name='section',
            name='img_6_tablet',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.get_unique_image_name),
        ),
        migrations.AlterField(
            model_name='section',
            name='img_7',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.get_unique_image_name),
        ),
        migrations.AlterField(
            model_name='section',
            name='img_7_mobile',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.get_unique_image_name),
        ),
        migrations.AlterField(
            model_name='section',
            name='img_7_tablet',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.get_unique_image_name),
        ),
    ]
